Repository ManageIQ/manageiq-gems-pending, pull requests merged in 2018-10, with the labels that each got.

#378 Don't set empty ENV values for database dumps
  lib/gems/pending/util/postgres_admin.rb
Labels: enhancement, hammer/yes

#379 Add support to send data on standard input when executing a command
  lib/gems/pending/util/MiqSshUtil.rb
Labels: enhancement

#380 [Changelog] Update for Sprint 96
  CHANGELOG.md
Labels: documentation

#383 [HAMMER] [Changelog] Add updates for beta1.1
  CHANGELOG.md
Labels: documentation

#371 DB Backups to Openstack Swift
  lib/gems/pending/util/miq_object_storage.rb
  lib/gems/pending/util/object_storage/miq_swift_storage.rb
  manageiq-gems-pending.gemspec
  spec/support/contexts/generated_tmp_files.rb
  spec/util/miq_file_storage_spec.rb
  spec/util/miq_object_storage_spec.rb
  spec/util/object_storage/miq_swift_storage_spec.rb
Labels: enhancement, hammer/yes

#384 Be more lenient for locked down ftp servers
  lib/gems/pending/util/miq_ftp_lib.rb
Labels: enhancement

#386 bump fog-openstack to v0.3
  manageiq-gems-pending.gemspec
Labels: dependencies

#391 Revert "Merge pull request #386 from gildub/bump_fog-openstack"
  manageiq-gems-pending.gemspec
Labels: bug

#393 Disable MiqFileStorage#handle_io_block error spec
  spec/util/miq_file_storage_spec.rb
Labels: bug/sporadic test failure
