Repository ManageIQ/manageiq-gems-pending, pull requests merged in 2018-05, with the labels that each got.

#349 [GAPRINDASHVILI] [Changelog] Update for gaprindashvili-3 release
  CHANGELOG.md
Labels: documentation

#350 Add .ruby-version to .gitignore
  .gitignore
Labels: developer

#351 Add pg_dump support back to PostgresAdmin
  lib/gems/pending/util/postgres_admin.rb
  spec/util/postgres_admin_spec.rb
Labels: enhancement, gaprindashvili/no

#352 Bump to ruby 2.4.4 for great justice
  .travis.yml
Labels: test
