Repository ManageIQ/manageiq-gems-pending, pull requests merged in 2018-09, with the labels that each got.

#361 MiqFileStorage interface and subclassing (with file splitting)
  lib/gems/pending/util/extensions/aws-sdk/s3_upload_stream_patch.rb
  lib/gems/pending/util/miq_file_storage.rb
  lib/gems/pending/util/miq_object_storage.rb
  lib/gems/pending/util/mount/miq_generic_mount_session.rb
  lib/gems/pending/util/mount/miq_glusterfs_session.rb
  lib/gems/pending/util/mount/miq_local_mount_session.rb
  lib/gems/pending/util/mount/miq_nfs_session.rb
  lib/gems/pending/util/mount/miq_s3_session.rb
  lib/gems/pending/util/mount/miq_smb_session.rb
  lib/gems/pending/util/object_storage/miq_s3_storage.rb
  spec/util/miq_file_storage_spec.rb
  spec/util/mount/miq_local_mount_session_spec.rb
  spec/util/mount/miq_s3_session_spec.rb
  spec/util/object_storage/miq_s3_storage_spec.rb
Labels: enhancement, gaprindashvili/no

#368 Add MiqFtpStorage
  lib/gems/pending/util/miq_object_storage.rb
  lib/gems/pending/util/object_storage/miq_ftp_storage.rb
  spec/support/contexts/generated_tmp_files.rb
  spec/support/custom_matchers/exist_on_ftp_server.rb
  spec/support/custom_matchers/have_size_on_ftp_server_of.rb
  spec/util/miq_file_storage_spec.rb
  spec/util/mount/miq_local_mount_session_spec.rb
  spec/util/object_storage/miq_ftp_storage_spec.rb
Labels: enhancement, gaprindashvili/no

#373 Changes to MiqPassword.sanitize_string to support URL encoded password.
  lib/gems/pending/util/miq-password.rb
  spec/util/miq-password_spec.rb
Labels: blocker, bug, gaprindashvili/yes

#375 [Changelog] Update for Sprint 95
  CHANGELOG.md
Labels: documentation

#376 [HAMMER] [Changelog] Update for Hammer Beta-1 release
  CHANGELOG.md
Labels: documentation

#377 Use a constant mask for encrypted fields
  lib/gems/pending/util/miq-password.rb
Labels: enhancement, hammer/yes, refactoring
