Repository ManageIQ/manageiq-gems-pending, pull requests merged in 2018-11, with the labels that each got.

#385 Adds full specs for restoring pg_dump and pg_basebackup backups
  .rspec_ci
  .travis.yml
  Rakefile
  lib/gems/pending/util/postgres_admin.rb
  manageiq-gems-pending.gemspec
  spec/ci_helper.rb
  spec/postgres_runner_helper.rb
  spec/spec_helper.rb
  spec/support/contexts/db_restore.rb
  spec/support/mixins/pg_environment_updater.rb
  spec/util/data/creating_pg_dump_and_pg_backup_files.md
  spec/util/data/pg_backup.tar.gz
  spec/util/data/pg_dump.gz
  spec/util/postgres_admin_spec.rb
Labels: hammer/yes, test

#397 Fixes some bugs with MiqS3Storage#download_single
  lib/gems/pending/util/object_storage/miq_s3_storage.rb
Labels: bug, hammer/yes

#395 [MiqGenericMountSession] Support @byte_count in #download_single
  lib/gems/pending/util/mount/miq_generic_mount_session.rb
  spec/util/mount/miq_local_mount_session_spec.rb
Labels: enhancement, hammer/yes

#398 Fixes and cleanup for MiqSwiftStorage
  lib/gems/pending/util/object_storage/miq_swift_storage.rb
  spec/util/object_storage/miq_swift_storage_spec.rb
Labels: bug, hammer/yes

#396 [MiqFtpStorage] Support @byte_count in #download_single
  lib/gems/pending/util/object_storage/miq_ftp_storage.rb
  spec/util/object_storage/miq_ftp_storage_spec.rb
Labels: enhancement, hammer/yes

#389 Determine magic number without shellout
  lib/gems/pending/util/postgres_admin.rb
  spec/util/postgres_admin_spec.rb
Labels: enhancement, hammer/yes

#390 Handle pipes for pg_restore
  lib/gems/pending/util/postgres_admin.rb
  spec/util/postgres_admin_spec.rb
Labels: enhancement, hammer/yes

#399 [MiqS3Storage] Support @byte_count in #download_single
  lib/gems/pending/util/object_storage/miq_s3_storage.rb
Labels: enhancement, hammer/yes

#402 Add :backup_type option to PostgresAdmin.restore
  lib/gems/pending/util/postgres_admin.rb
  spec/util/postgres_admin_spec.rb
Labels: enhancement, hammer/yes

#394 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-6
  CHANGELOG.md
Labels: documentation

#388 [HAMMER] [Changelog] Update for Hammer Beta2
  CHANGELOG.md
Labels: documentation

#387 [Changelog] Add Sprint 97 and Hammer Beta1 updates
  CHANGELOG.md
Labels: documentation

#401 [MiqFileStorage] Add #magic_number_for
  lib/gems/pending/util/miq_file_storage.rb
  lib/gems/pending/util/object_storage/miq_ftp_storage.rb
  spec/util/mount/miq_local_mount_session_spec.rb
  spec/util/object_storage/miq_ftp_storage_spec.rb
Labels: enhancement, hammer/yes

#410 Fixes to swift storage
  lib/gems/pending/util/object_storage/miq_swift_storage.rb
  spec/util/object_storage/miq_swift_storage_spec.rb
Labels: enhancement, hammer/yes

#409 [HAMMER] [Changelog] Update for Hammer RC-1
  CHANGELOG.md
Labels: documentation

#406 Use Gem::Package for tar pg restore unpacking via download streaming
  lib/gems/pending/util/postgres_admin.rb
  manageiq-gems-pending.gemspec
Labels: enhancement, hammer/yes

#411 [Changelog] Update for Sprint 99
  CHANGELOG.md
Labels: documentation

#412 [HAMMER] [Changelog] Update for Hammer RC2
  CHANGELOG.md
Labels: documentation
