Repository ManageIQ/manageiq-gems-pending, pull requests merged in 2018-08, with the labels that each got.

#357 S3 db restore
  lib/gems/pending/util/mount/miq_s3_session.rb
Labels: enhancement

#359 Remove Debug Messages
  lib/gems/pending/util/mount/miq_s3_session.rb
Labels: bug

#362 Update PG_DUMP_MULTI_VALUE_ARGS for underscore args
  lib/gems/pending/util/postgres_admin.rb
  spec/util/postgres_admin_spec.rb
Labels: enhancement, gaprindashvili/no

#363 [Changelog] Update for Sprint 92
  CHANGELOG.md
Labels: documentation

#364 Use --xlog-method=stream for pg_basebackup
  lib/gems/pending/util/postgres_admin.rb
Labels: bug

#367 Revert to using --xlog-method fetch for postgres backup
  lib/gems/pending/util/postgres_admin.rb
Labels: bug

#365 Use STDOUT for pg_basebackup
  lib/gems/pending/util/postgres_admin.rb
Labels: enhancement, gaprindashvili/no

#370 Use correct variable name for PostgresAdmin
  lib/gems/pending/util/postgres_admin.rb
Labels: bug, gaprindashvili/no

#369 [FINE] Update deps for google
  manageiq-gems-pending.gemspec
Labels: dependencies
