Repository ManageIQ/manageiq-gems-pending, pull requests merged in 2019-05, with the labels that each got.

#431 Fix uninitialized warning in vmdb-logger.rb
  lib/gems/pending/util/vmdb-logger.rb
  spec/util/vmdb-logger_spec.rb
Labels: changelog/no, cleanup, technical debt

#432 Bump master travis.yml to ruby 2.4.6
  .travis.yml
Labels: changelog/no, test

#434 [HAMMER] Bump hammer travis.yml to ruby 2.4.6
  .travis.yml
Labels: test

#435 Introduce FirmwareUpdateError
  lib/gems/pending/util/miq-exception.rb
Labels: enhancement
