Repository ManageIQ/manageiq-gems-pending, pull requests merged in 2019-10, with the labels that each got.

#449 update aws-sdk gem to v3
  lib/gems/pending/util/extensions/aws-sdk/s3_upload_stream_patch.rb
  lib/gems/pending/util/object_storage/miq_s3_storage.rb
  manageiq-gems-pending.gemspec
Labels: dependencies

#447 [MiqGenericMountSession] Fix .source_for_log
  lib/gems/pending/util/mount/miq_generic_mount_session.rb
Labels: hammer/yes, ivanchuk/yes

#450 Test ruby 2.5.7/2.6.5, see: ManageIQ/manageiq#19414
  .travis.yml
Labels: changelog/no, test
