Repository ManageIQ/manageiq-gems-pending, pull requests merged in 2019-03, with the labels that each got.

#422 Change pg_basebackup xlog-method option to wal-method
  .travis.yml
  lib/gems/pending/util/postgres_admin.rb
  spec/ci_helper.rb
  spec/support/contexts/db_restore.rb
  spec/util/data/creating_pg_dump_and_pg_backup_files.md
  spec/util/data/pg_backup.tar.gz
  spec/util/data/pg_dump.gz
Labels: enhancement, wip

#425 [Changelog] Update for Sprint 107
  CHANGELOG.md
Labels: documentation

#426 Add put_file method
  lib/gems/pending/util/MiqSshUtil.rb
Labels: enhancement, hammer/yes

#427 Update supported ruby versions on Travis
  .travis.yml
Labels: changelog/no, test

#424 Remove miq-password
  lib/gems/pending/util/miq-password.rb
  lib/gems/pending/util/vmdb-logger.rb
  manageiq-gems-pending.gemspec
  spec/support/custom_matchers/be_decrypted.rb
  spec/support/custom_matchers/be_encrypted.rb
  spec/support/custom_matchers/be_encrypted_version.rb
  spec/util/vmdb-logger_spec.rb
Labels: technical debt

#421 Extract MiqStats in favor of Math extension in more_core_extensions
  lib/gems/pending/util/extensions/miq_stats.rb
  manageiq-gems-pending.gemspec
Labels: refactoring
