Repository ManageIQ/manageiq-gems-pending, pull requests merged in 2019-07, with the labels that each got.

#437 MiqSshUtil updates
  lib/gems/pending/util/MiqSshUtil.rb
  spec/util/miq_ssh_util_spec.rb
Labels: bug, changelog/yes, hammer/yes

#439 [Changelog] Update for Sprint 115
  CHANGELOG.md
Labels: documentation

#441 [Changelog] Update for Hammer-9
  CHANGELOG.md
Labels: documentation, hammer/yes

#442 [Changelog] Update for Ivanchuk Beta1
  CHANGELOG.md
Labels: documentation, ivanchuk/yes
