Repository ManageIQ/manageiq-gems-pending, pull requests merged in 2020-02, with the labels that each got.

#458 Update sys-proctable gem to 1.2.x
  lib/gems/pending/util/miq-process.rb
  manageiq-gems-pending.gemspec
Labels: enhancement

#461 Refactor MiqProcess
  lib/gems/pending/util/miq-process.rb
  spec/util/miq-process_spec.rb
Labels: refactoring

#463 Bump version of rake to >=12.3.3 for CVE-2020-8130
  manageiq-gems-pending.gemspec
Labels: bug, dependencies
