Repository ManageIQ/manageiq-gems-pending, pull requests merged in 2020-10, with the labels that each got.

#490 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: dependencies

#492 cleanup travis.yml
  .travis.yml
Labels: developer

#493 Remove miq-hash
  lib/gems/pending/util/extensions/miq-hash.rb
  spec/util/extensions/miq-hash_spec.rb
Labels: technical debt

#495 Remove miq-benchmark
  lib/gems/pending/util/extensions/miq-benchmark.rb
  spec/util/extensions/miq-benchmark_spec.rb
Labels: technical debt

#491 Use manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-gems-pending.gemspec
Labels: developer, enhancement

#497 Fix .rubocop_local.yml
  .rubocop_local.yml
Labels: developer

#498 Bump more_core_extensions to 4.3
  manageiq-gems-pending.gemspec
Labels: dependencies, enhancement

#496 Remove miq-to_i_with_method
  lib/gems/pending/util/extensions/miq-to_i_with_method.rb
  spec/util/extensions/miq-to_i_with_method_spec.rb
Labels: technical debt

#494 Remove miq-object
  lib/gems/pending/util/extensions/miq-object.rb
  spec/util/extensions/miq-object_spec.rb
Labels: technical debt
