Repository ManageIQ/manageiq-gems-pending, pull requests merged in 2020-07, with the labels that each got.

#482 Remove MiqSockUtil
  lib/gems/pending/util/MiqSockUtil.rb
Labels: cleanup

#481 update mce to 4.0
  manageiq-gems-pending.gemspec
Labels: dependencies, enhancement

#483 Deprecate #to_miq_a
  lib/gems/pending/util/extensions/miq-array.rb
  spec/util/extensions/miq-array_spec.rb
Labels: technical debt
