Repository ManageIQ/manageiq-gems-pending, pull requests merged in 2020-05, with the labels that each got.

#469 Remove miq_tempfile.rb
  lib/gems/pending/util/miq_tempfile.rb
Labels: technical debt

#471 remove unused SyncDebug
  lib/gems/pending/util/SyncDebug.rb
  lib/gems/pending/util/test/SyncDebugTest.rb
  lib/gems/pending/util/test/SyncDebug_watchdogTest.rb
Labels: cleanup

#473 Removing deprecated Gemnasium badge
  README.md
Labels: developer

#470 Remove MiqSshUtil.rb
  lib/gems/pending/util/MiqSshUtil.rb
  spec/util/miq_ssh_util_spec.rb
Labels: technical debt

#472 remove unused MIQEncode.base24Decode method
  lib/gems/pending/util/miq-encode.rb
  spec/util/miq-encode_spec.rb
Labels: cleanup

#475 Use Etc for num_cpus
  lib/gems/pending/util/miq-system.rb
Labels: refactoring
