Repository ManageIQ/manageiq-gems-pending, pull requests merged in 2021-01, with the labels that each got.

#506 Remove miq-metakit.rb
  lib/gems/pending/util/miq-metakit.rb
Labels: cleanup

#509 Remove miq-unicode.rb
  lib/gems/pending/util/miq-unicode.rb
  lib/gems/pending/util/win32/miq-powershell.rb
  spec/util/miq-unicode_spec.rb
Labels: technical debt

#508 don't define duplicate getter for logger
  lib/gems/pending/util/mount/miq_generic_mount_session.rb
Labels: refactoring

#511 Hide the generic run_command behind specific mount/umount API
  lib/gems/pending/util/mount/miq_generic_mount_session.rb
  lib/gems/pending/util/mount/miq_glusterfs_session.rb
  lib/gems/pending/util/mount/miq_nfs_session.rb
  lib/gems/pending/util/mount/miq_smb_session.rb
  spec/util/mount/miq_generic_mount_session_spec.rb
Labels: refactoring
