Repository ManageIQ/manageiq-gems-pending, pull requests merged in 2024-08, with the labels that each got.

#582 Upgrade rexml to 3.3.3+ for CVE-2024-41123 and CVE-2024-41946
  manageiq-gems-pending.gemspec
  spec/util/miq-xml_spec.rb
Labels: dependencies, security fix, radjabov/yes?

#583 Use ruby 3.1 and rails 7 for code coverage
  .github/workflows/ci.yaml
Labels: developer, test

#590 Drop Rails 6.1 testing and add Rails 7.1 and 7.2 testing
  .github/workflows/ci.yaml
  Gemfile
  manageiq-gems-pending.gemspec
Labels: dependencies, test, radjabov/yes?

#589 Bump rexml to 3.3.6 for CVE-2024-43398
  manageiq-gems-pending.gemspec
Labels: dependencies, radjabov/yes
